### ISSUE TITLE
Install PKHeX.Core via MyGet

### ISSUE THREAD

**Issue by leo60228** [architdate/PKHeX-Plugins#11]
Officially available at https://www.myget.org/F/projectpokemon/api/v3/index.json. See kwsch/PKHeX#2158.

**Comment by architdate** [comment]
Thanks for the suggestion, This is a great idea. will definitely implement this.

**Comment by architdate** [comment]
Reverted [`086d193`](https://github.com/architdate/PKHeX-Plugins/commit/086d193a8b5f3d65f270f9de664fcb3503d9f460)
Opening this issue again for the timebeing. Will re implement when PKHeX.Core is moved to NuGet instead of MyGet (evandixon seems to be handling that in [kwsch/PKHeX#2158](https://github.com/kwsch/PKHeX/issues/2158).)
