### ISSUE TITLE
Importing from Showdown Unable to Make Set

### ISSUE THREAD

**Issue by Galaxad** [architdate/PKHeX-Plugins#146]
**Describe the problem**
Timed out I think, said exhausted 0/132 encounters.

[Invalid] [DateTime: 9/1/2022 2:35:47 AM]
Ferrothorn (M) @ Leftovers
IVs: 0 Spe
EVs: 252 HP / 108 Def / 150 SpD
Ability: Iron Barbs
Sassy Nature
- Seed Bomb
- Gyro Ball
- Leech Seed
- Protect

**To Reproduce**
Trainer Data was used. I have been having another issue with that which I'll make a second post about in a minute
Ferrothorn (M) @ Leftovers  
Ability: Iron Barbs  
EVs: 252 HP / 108 Def / 150 SpD  
Sassy Nature  
IVs: 0 Spe  
- Seed Bomb  
- Gyro Ball  
- Leech Seed  
- Protect

**Expected behavior**
I expected it to not have a problem with the pokemon. I also made this exact set a couple of days ago with no issues and when I take that set from my box to the legality checker it passes, but importing flags it.

**Screenshots**
![image](https://user-images.githubusercontent.com/52763964/187859612-129c458c-17b0-4eb9-ab86-480b0a304084.png)
![image](https://user-images.githubusercontent.com/52763964/187859705-33032bcf-c5e5-4cdd-9623-5fc3652f4e10.png)

**Additional context**
I was using 220626 b version of PKHeX and not the 220831 version

**Comment by architdate** [comment]
What game did you try to generate this on? I tried this in SW/SH and had no issues and it genned instantly. I also tried to generate this on BD/SP without any issues

**Comment by Galaxad** [comment]
I was doing this on SwSh. I also tried it with a Gallade and Venusaur and the same error happened of "0/some number exhausted". I tried closing and reopening the program. I do have the 220831 version but it's all in a different folder and I copied the existing files and pasted them to the new version, so I should have two full versions of PKHeX and plugins. Is it possible that by loading this save in the newest update and exporting it and then later opening it in the older version that messed it up?

**Comment by architdate** [comment]
I don't think that should be an issue. Can you perhaps send me the pkm that is being used through your trainerdata? I can test that perhaps?

**Comment by Galaxad** [comment]
Sure! So I have two pkm in the trainer folder, this is the first one in the folder (which has the trainer data that has been imported every time)
[812 - Guy - AB603B580936.zip](https://github.com/architdate/PKHeX-Plugins/files/9471705/812.-.Guy.-.AB603B580936.zip)
This is the second one
[888 - Zacian - 04488E18811D.zip](https://github.com/architdate/PKHeX-Plugins/files/9471713/888.-.Zacian.-.04488E18811D.zip)

**Comment by Lusamine** [comment]
I got @Galaxad's folder on Discord and this is the problem:

Since previous release, Auto-Legality Mod has been adding an unnecessary non-OT HT with language Japanese.  This also occurs on latest commits of PKHeX and Plugins.
![image](https://user-images.githubusercontent.com/30205550/187987893-6ddd66b9-1192-4113-affc-7a3c7ddaab11.png)
Note that this is trainer data matching my save file from a mon captured on this save.

The other part of the problem was they had this setting enabled in base PKHeX.
![image](https://user-images.githubusercontent.com/30205550/187988077-39acdbf2-549c-4a26-a157-87683707f555.png)

Since their save isn't Japanese, every single mon would be flagged for not matching the current save file.
![image](https://user-images.githubusercontent.com/30205550/187988393-16f828d8-ef8b-4301-9b62-082d480f85f0.png)
