### ISSUE TITLE
Error message from ALM

### ISSUE THREAD

**Issue by Zpanther1** [architdate/PKHeX-Plugins#156]
Every time I try to use ALM from pkhex inputted mons or showdown mods I get the same error message. I have tried on various different pokemon including maushold (4 and 3), gulpin, and wiglet. 
![223](https://user-images.githubusercontent.com/120697115/208009138-12988028-9605-429b-acf1-39f34f838b5e.PNG)
![1234](https://user-images.githubusercontent.com/120697115/208009159-00e0c2ef-e078-483a-8c9f-9cdb3616165e.PNG)

**Comment by Lusamine** [comment]
You should be validating the sets on Showdown first per the wiki.
If you have validated the set and the set continues to fail to generate, please post the set.

**Comment by architdate** [comment]
Are you using a showdown set to generate them? I can generate Maushold just fine

**Comment by Zpanther1** [comment]
Could you please link the wiki page? Much appreciated

**Comment by Lusamine** [comment]
![image](https://user-images.githubusercontent.com/30205550/208009927-5d7fa24f-6782-4ae8-99c5-a7e428839412.png)
Click here and use the "Getting Started" page.
I am closing this since it looks like you tried to use the mod without following the guide.
You can open a new issue if you find a set that's legal on Showdown and doesn't generate with the mod.

**Comment by architdate** [comment]
> Could you please link the wiki page? Much appreciated

https://github.com/architdate/PKHeX-Plugins/wiki/Getting-Started-with-Auto-Legality-Mod

Feel free to browse the wiki for further questions. If you still have an issue generating your pokemon, reopen the issue once you have followed through all the instructions and recommendations as stated in the wiki

**Comment by Zpanther1** [comment]
I followed through the guide and It said my team was valid for gen 9 ubers and it still wont import.

**Comment by architdate** [comment]
Could you post the set you used to import here?

**Comment by Zpanther1** [comment]
Maushold-Four  
Ability: Friend Guard  
Shiny: Yes  
EVs: 16 HP / 36 Atk / 68 Def / 36 SpA / 52 SpD / 48 Spe  
- Agility  
- Seed Bomb  
- Crunch  
- Encore

**Comment by architdate** [comment]
![image](https://user-images.githubusercontent.com/17220860/208011164-70c8496b-157e-458d-8612-8ab9cfb95eab.png)
![image](https://user-images.githubusercontent.com/17220860/208011264-4da00e62-a5fc-4a29-93ec-a2f178215ae2.png)
![image](https://user-images.githubusercontent.com/17220860/208011286-d1a1e844-61de-482e-8a3d-94c26e8da686.png)

I was able to successfully import it

Are you sure you are on the latest build for both PKHeX and Plugins?

**Comment by Zpanther1** [comment]
How can I check?

**Comment by architdate** [comment]
I was also able to generate a whole box of them, so it is unlikely that this is a race condition either
![image](https://user-images.githubusercontent.com/17220860/208011499-ca91b894-5bb8-4119-8593-d316ab833b5c.png)

**Comment by Zpanther1** [comment]
Can I put the files here and you can check if they are the lastest ones?

**Comment by architdate** [comment]
> How can I check?

If you were not notified about a new release when you started the program, you should be on the latest version.

If you copy your set and go to `Tools > Auto-Legality Mod > Import with Auto-Legality Mod` it should generate just fine. 
Alternatively you can copy the set and press `Ctrl + I` to generate it.



> Can I put the files here and you can check if they are the lastest ones?

Please don't do that. It is best if you try it yourself. 

I am closing this since I cannot replicate your behavior. If you are trying to legalize pokemon by manually inputting fields, please don't do that and follow the import instructions i stated above
