### ISSUE TITLE
Can't find rebuild all when right clicking solution

### ISSUE THREAD

**Issue by Mattlau04** [architdate/PKHeX-Plugins#16]
I'm not actually sure what the solution itself is, but i assume it's the sln file

**Comment by architdate** [comment]
9d8231b is the commit that breaks building. At the moment the latest core path is set to my own local machine since nuget has not been updated for PKHeX.Core as you can see [here](https://www.nuget.org/packages/PKHeX.Core) 

If you would like to build, you would have to reference the core project to your own local directory with an updated PKHeX.Core since the nuget one is still pre SWSH changes. I'll keep this issue open and close it once I have reverted the csproj path to use nuget

**Comment by Mattlau04** [comment]
I'm not really good with visual studio so i'll just wait for the next release
