### ISSUE TITLE
Level on specific Showdown import not respected

### ISSUE THREAD

**Issue by ReignOfComputer** [architdate/PKHeX-Plugins#45]
Interesting phenomena:

Importing:

> Cobalion
> Level: 49
> Adamant Nature
> – Sacred Sword

Will result in a Level 49 Cobalion with the origin of Black 2 (Level 45 Met).

Importing:

> Cobalion
> Level: 60
> Adamant Nature
> – Sacred Sword

Will result in a Level 60 Cobalion with the origin of Ultra Sun (Level 60 Met).

Importing:

> Cobalion
> Level: 51
> Adamant Nature
> – Sacred Sword

Will result in a Level 51 Cobalion with the origin of Omega Ruby (Level 50 Met).

BUT importing:

> Cobalion
> **Level: 50**
> Adamant Nature
> – Sacred Sword

Will result in a **Level 100** Cobalion with the origin of Omega Ruby (Level 50 Met).

**Comment by kwsch** [comment]
It's because asking for a level 50 is usually a user-error as they're trying to get something legal for VGC use (where things are downleveled to 50). Auto Legality ignores their request for a level 50, and keeps it as level 100 in order to get something legal.

Stuff like "Level 50 Hydreigon" isn't possible without the VGC downleveling.

https://github.com/architdate/PKHeX-Plugins/blob/6aba2abe236a8b62356ab5027dd8f5a523a97370/PKHeX.Core.AutoMod/AutoMod/ShowdownEdits.cs#L101-L103
