### ISSUE TITLE
LiveHeX crashing switch 

### ISSUE THREAD

**Issue by Wolfling1** [architdate/PKHeX-Plugins#84]
**Describe the bug**
Sometimes when clicking write current box with LiveHeX, it crashes my switch completely (atmosphere crash)

**To Reproduce**
It seems absolutely random when it crashes, but im just doing write to box injects

**Expected behavior**
Not to crash

**Screenshots**

**Additional context**

**Comment by berichan** [comment]
Try deleting/clearing your atmosphere logs and reinstall sys-botbase 1.6. What's the title ID shown in the ams crash?

**Comment by Wolfling1** [comment]
I don't have the title ID on me but i'll get it next time it crashes.
I'll try clearing the logs and reinstalling, thanks.

**Comment by Lusamine** [comment]
This can happen if your write is interrupted, such as through a weak connection.  Make sure you wait adequate time after writing before trying to change anything else.  Ensure you have strong wifi and you are close to your router.  Other than what berichan suggested, there's not much to be done since it's usually specific to your connection.

**Comment by Wolfling1** [comment]
It's definitely not my connection, my connection is very good (never below level 3 on switch) and never drops out
This also doesnt happen with ACNH live injecting

The tile id on atmosphere crash is 430000000000000B.

**Comment by Wolfling1** [comment]
Also, to clear atmosphere logs, what should i delete? Just crash_reports?
